### PR TITLE
Selfhost font Open Sans

### PR DESCRIPTION
**Pull request by Rotzbua**
less dependency on google services

### CODE REVIEW

**Comment by t-paul** [comment]
Ooof, that's a lot of font files :smile:. I wonder if it would be better starting slowly. At this point there's not much text other than english and a little bit of german on the pages.

Is there a simple way to trim the list?

**Comment by Rotzbua** [comment]
The browser detects automatically which font and unicode range is required.
If you wish I can remove all non latin font files?

**Comment by t-paul** [comment]
Yes, I think it's better to keep the repo smaller for now. We can always extend in case we find someone who would like to add and maintain other languages.

**Comment by Rotzbua** [comment]
Now limited to `latin` charset and font files reduced to 24.

**Review by t-paul — APPROVED** [review]

**Pull request merged**
