### PR TITLE
Michael at oz cheetsheet colours

### PR DESCRIPTION
**Pull request by MichaelAtOz**
How about this?
cheatsheet color MM

### CODE REVIEW

**Comment by MichaelAtOz** [comment]
I just noticed I dropped 'Cheatsheet' from the title. 
Do we need it, tautology?

**Comment by t-paul** [comment]
Looks good.

**Comment by MichaelAtOz** [comment]
> You’re all set—the MichaelAtOz:MichaelAtOz-cheetsheet-colours branch can be safely deleted. 

> This branch [MichaelAtOz:master] is 4 commits behind openscad:master. 

@t-paul so I should delete my branch then pull the original master into my fork again. Is that how it works?

**Comment by t-paul** [comment]
If you do it the other way around, git will also notice that things are merged, so it should be possible to delete via `git branch -d` instead of forcing it by `git branch -D`.

If the local repo is cloned from the personal github and has the openscad repo as `upstream` remote like
```
$ git remote -v
origin    git@github.com:t-paul/openscad.git (fetch)
origin    git@github.com:t-paul/openscad.git (push)
upstream  git@github.com:openscad/openscad.git (fetch)
upstream  git@github.com:openscad/openscad.git (push)
```
 the following should update everything.
```
git checkout master
git pull upstream master    # sync local master with openscad repo
git branch -d cheatsheet    # delete local branch (still remains on the personal repo)
git push                    # push updated master to personal repo
```

**Pull request merged**
