### PR TITLE
Customizer post

### PR DESCRIPTION
**Pull request by kintel**
@t-paul @amarjeetkapoor1 Does this look good?

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
Post looks good to me but are the binaries updated.

**Comment by t-paul** [comment]
Yes, nice summary. So we'll update the binaries from the `gsoc2016` branch and publish then?

**Comment by amarjeetkapoor1** [comment]
Would binaries be created from recent code in gsco2016 branch or from some particular commit in that  branch

**Comment by kintel** [comment]
@amarjeetkapoor1 The binary links you posted in your blog was dated 2016.06.30. If you want to update the blog post, just confirm which binaries you'd like to see and we can build them.
I don't have any preference - I think you'll know best what commit we should publish :)

**Comment by kintel** [comment]
PS. I'll add one more sentence asking people to contribute comments and ideas to the mailing list and irc.

**Comment by amarjeetkapoor1** [comment]
I would like to get latest binaries made of latest commit in gsoc2016 branch.

**Comment by kintel** [comment]
ok, I'll build for Mac and give you the new link.

**Comment by kintel** [comment]
New Mac binaries: http://files.openscad.org/snapshots/OpenSCAD-2016.07.15-gsoc2016.dmg

**Pull request merged**
