### PR TITLE
corrected typo

### PR DESCRIPTION
**Pull request by fredbar**
« modeller » only takes 1 « l »

### CODE REVIEW

**Comment by kintel** [comment]
This really depends on what flavour/flavor of English you speak.
For the language itself, we're using american spelling, but web resources and documentation is a bit of a mashup, largely due to the fact that most OpenSCAD contributions are made by Europeans.

I'll leave this open for a bit as this influences the logo tagline as well.

**Comment by fredbar** [comment]
Ok, i understand.
Coming from 3D field (not CAD), it did hurt me to read with two "l". And i'm european, too.
The logo tagline is the reason why i acted. I really thought that it had to be "corrected".

**Comment by MichaelAtOz** [comment]
Given the change I'm about to do, I'd like to kill this.
Is closing it enough?

**Comment by MichaelAtOz** [comment]
>  kintel commented on 4 Mar 2015 
> I'll leave this open for a bit as this influences the logo tagline as well.

'for a bit'...

Closing, as we are sticking with the original double ell spelling.

**Pull request closed without merging**
