### PR TITLE
Fixed links on community page sidebar

### PR DESCRIPTION
**Pull request by moltra**

### CODE REVIEW

**Comment by t-paul** [comment]
Those links are supposed to scroll to the appropriate section, not link directly. For some reason that does not work in Chrome, it does in Firefox. I think it's some of the included JavaScripts breaking that.

**Comment by moltra** [comment]
Have you thought about migrating the website to Wordpress.  Would be very easy to edit the content and add images.

**Comment by t-paul** [comment]
Yes, I think there's even an incomplete setup for that. Not really moving forward due to lack of time.

**Comment by moltra** [comment]
I have multiple website on wordpress, I can do it if you want me to

**Comment by t-paul** [comment]
@kintel, what do you think. Is there a way to revive the wordpress prototype?

**Comment by moltra** [comment]
I can clone the site in Wordpress like it is now, and you can see what it would look like.
and how it would be to maintain.

**Comment by t-paul** [comment]
I'm not sure where it's hosted, DNS looks like a namecheap hosted WordPress. The site link is https://www2.openscad.org/.

**Comment by moltra** [comment]
looks pretty good, do you have a list of things that need to be done yet?

**Comment by MichaelAtOz** [comment]
That needs to be rebranded back to the new colours (ie as site is now) & slogan.

**Comment by t-paul** [comment]
I believe it would be mostly syncing up with the current site (missing content, dynamic links for snapshot download, new library section, conversion of the gallery). Maybe the menu could also do with a little bit of reshuffling, e.g. the Gallery seems a bit lost under Community.

@MichaelAtOz I think that is the new color scheme, no? I'm not sure, I should have a couple of flyers somewhere @kintel gave me last FOSDEM. I seem to remember those were matching the style of that design/branding.

**Comment by moltra** [comment]
That is easy to do in Wordpress.  

Also needs a CDN and maybe a little back end tweaking to speed up the website.

**Comment by MichaelAtOz** [comment]
> @MichaelAtOz I think that is the new color scheme, no? I'm not sure, I should have a couple of flyers somewhere @kintel gave me last FOSDEM. I seem to remember those were matching the style of that design/branding.

The current site colours/slogan were set when I did the Merch.
Capture-slogan
Matches:
(it's not clear in the photo, but the background colour of the mug and notebook, is the OpenSCAD cornfield, same as the site edge/background)
Capture-merch

**Comment by t-paul** [comment]
Closing, things have moved on. Original issue was fixed removing broken JQuery calls.

**Pull request closed without merging**
