### PR TITLE
Added $preview to the cheatsheet.

### PR DESCRIPTION
**Pull request by nophead**
Simple change but don't know how to test this.

### CODE REVIEW

**Comment by MichaelAtOz** [comment]
I have a copy of the web site on my PC.
I just downloaded this file, dropped it in the right place.
Works, but needs the box width increased.
dollar-preview
Also https://github.com/openscad/openscad.github.com/blob/35017e714167a3d4a3fdc276d8b5065c44cbcb42/assets/img/openSCAD_cheat_sheet.png needs updating. Note that those boxes jump around with zoom level, probably want a 'nice' layout.

**Comment by nophead** [comment]
Thanks, I hadn't realised it was as simple as downloading it, I thought it would need a server.

I have fixed the layout and updated the picture but it now contains the date of the release so it might need updating again. Also the sheet is considerable bigger compared to the old image due to new sections so it ends up with very small text when compressed into documentation page.

**Comment by MichaelAtOz** [comment]
> Also the sheet is considerably bigger compared to the old image 

I don't think that matters (?) as clicking it gets a non-embedded version.

> contains the date of the release 

Yeh...perhaps "OpenSCAD v2015.03 (ⓐv2018.n, ⓑv2018.n+1 etc) and flag the new stuff??

**Comment by MichaelAtOz** [comment]
>  thought it would need a server

Hopefully we never need to over-complicate it...

**Comment by MichaelAtOz** [comment]
> contains the date of the release

Alternatively leave the 2015.03 as-is, show a link to 'Development Cheatsheet'?

**Comment by t-paul** [comment]
I merged the changes into the [snapshot cheatsheet](http://www.openscad.org/cheatsheet/snapshot.html) (dropping the image update for now as that is for the release version).

**Pull request closed without merging**
